### ISSUE TITLE
String interpolation syntax for Text SwiftUI widget throws an error

### ISSUE THREAD

**Issue by kvenn** [jansorg/swift-plugin#26]
The following code shows an error

```swift
        Text("Updated \(startDate, style: .relative) ago")
            .font(.system(size: 10))
            .foregroundColor(Color.white.opacity(0.5))
```

Error:
> '!', '#', '#if', '#keypath', '&', '(', '.', ':', ';', <, <branch statement>, <compiler control statement>, <conditional expression>, <control transfer statement>, <declaration>, <infix expression>, <labeled statement>, <literal expression>, <loop statement>, <postfix expression>, <primary expression identifier>, <selector expression>, '?', Any, Self, '\', _, await, defer, do, self, super, try, '{' or '}' expected, got '('

<img width="498" alt="image" src="https://github.com/jansorg/swift-plugin/assets/1782467/2310789a-e71b-4c0e-962c-69f4c9ce9dd2">

This error causes the rest of the file to not work too great.

**Comment by jansorg** [comment]
Thanks!
I've fixed this for the next update. The official grammar seems to be lacking a few enhancements, reported at https://github.com/apple/swift-book/issues/295

**Comment by kvenn** [comment]
Great! Looking forward to it 🥳

**Comment by jansorg** [comment]
The latest version should have the fix already. Or doesn't it work for you?

**Comment by kvenn** [comment]
I think I'm on the latest and I'm still seeing it.

<img width="239" alt="image" src="https://github.com/jansorg/swift-plugin/assets/1782467/0a88442b-9f04-477b-b311-0b17825a8d2e">
<img width="964" alt="image" src="https://github.com/jansorg/swift-plugin/assets/1782467/3422ec28-bb05-4cfa-8128-5e06f3db0073">

**Comment by jansorg** [comment]
@kvenn That's weird, the latest version is 1.0.0, https://plugins.jetbrains.com/plugin/22150-swift-support/edit/versions/stable/527403
Try `Help > Check for updates` or verify the update at `Settings > Plugins`. Please let me know if it's still not working for you.

**Comment by kvenn** [comment]
Very weird! I'm fully unable to update to that version. I've restarted the IDE, uninstalled and reinstalled the plugin, and tried downloading from web but it just deeplinks to 0.21.*.

**Comment by jansorg** [comment]
Are you saying that 0.21.* is installed when you download 1.0 at https://plugins.jetbrains.com/plugin/22150-swift-support/versions/stable/527403 and install manually via `Settings > Plugins > (Gear wheel) > Install from disk`?

**Comment by kvenn** [comment]
Thanks for trying to help me through this lol. No idea why I'm struggling so hard.

<img width="404" alt="image" src="https://github.com/jansorg/swift-plugin/assets/1782467/6af0b8a8-ee8a-4e98-8e6d-bbe7e6e7e1e6">

> Plugin 'Swift Support' (version '1.0.0.345-241') is not compatible with the current version of the IDE, because it requires build 241.15989.0 or newer but the current build is IU-241.14494.240

So I guess IntelliJ ultimate is lagging behind Intellij? And that's why the latest plugin isn't available to me.

**Comment by jansorg** [comment]
`241.15989.0` is 2024.1.1, https://www.jetbrains.com/idea/download/other.html
IntelliJ Ultimate and Community have the same build number, 2024.1.1 should be available to you.

**Comment by kvenn** [comment]
As we all had feared, it was indeed user error.

I had to use the JetBrains Toolbox App to update IntelliJ. 

The bug is fixed and I see you've been hard at work making this plugin awesome! Just did the yearly subscription.
